version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "5000:5000"
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - MONGOPORT=27017
  postgres:
    image: "postgres:latest"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  mongo:
    image: "mongo:latest"
    volumes:
      - ./mongo-data:/data/db
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
